import type { Collection, AbayanType, Testimonial, NavLink } from '@/types'

export const BRAND = {
  name:            'HOOR',
  tagline:         'Elegance in Modesty',
  subTagline:      'Premium modern abayas for the graceful woman.',
  description:     'Premium modest fashion curated for women who move through the world with quiet confidence.',
  location:        'Mangalore, India',
  instagram:       'https://instagram.com/hoor.ind',
  instagramHandle: '@hoor.ind',
  whatsapp:        'https://wa.me/917899109549',
  whatsappMsg:     'Hello HOOR, I would like to enquire about your collection.',
  phone:           '+91 78991 09549',
  email:           'hoor.ind1@gmail.com',
  ownerName:       'Shiza Ishel',
} as const

export const NAV_LINKS: NavLink[] = [
  { href: '/',           label: 'Home'       },
  { href: '/shop',       label: 'Shop'       },
  { href: '/collection', label: 'Collection' },
  { href: '/lookbook',   label: 'Lookbook'   },
  { href: '/about',      label: 'Story'      },
  { href: '/contact',    label: 'Contact'    },
]

export const COLLECTIONS: Collection[] = [
  {
    id: 'al-noor',
    name: 'Al Noor',
    category: 'Signature',
    description: 'A luminous silhouette that commands attention with complete restraint.',
    price: '₹8,500',
    priceNum: 8500,
    tag: 'Signature',
    featured: true,
    aspect: 'portrait',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Midnight Black', hex: '#141412' },
      { name: 'Ivory Cream', hex: '#F8F4EE' },
      { name: 'Mocha Nude', hex: '#D4B8A8' },
    ],
    fabric: '100% Premium Nida Fabric',
    details: [
      'Flowing full-length silhouette',
      'Concealed front zipper closure',
      'Elasticated cuffs with pearl button detail',
      'Lined throughout for complete coverage',
    ],
    careInstructions: ['Hand wash in cold water', 'Do not tumble dry', 'Iron on low heat', 'Store on a hanger'],
  },
  {
    id: 'al-raha',
    name: 'Al Raha',
    category: 'Classic',
    description: 'For the woman who moves through the world with quiet, unshakeable confidence.',
    price: '₹7,200',
    priceNum: 7200,
    tag: 'New',
    featured: true,
    aspect: 'portrait',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Midnight Black', hex: '#141412' },
      { name: 'Deep Navy', hex: '#1B2A4A' },
    ],
    fabric: '100% Crepe Fabric',
    details: [
      'Classic open-front abaya',
      'Wide bell sleeves',
      'Raw hem finish',
      'Lightweight and breathable',
    ],
    careInstructions: ['Machine wash cold, gentle cycle', 'Tumble dry low', 'Iron on medium heat'],
  },
  {
    id: 'al-wafa',
    name: 'Al Wafa',
    category: 'Luxury',
    description: 'Timeless in form. Modern in every way that matters.',
    price: '₹9,800',
    priceNum: 9800,
    tag: 'Exclusive',
    featured: true,
    aspect: 'portrait',
    sizes: ['S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Midnight Black', hex: '#141412' },
      { name: 'Champagne Gold', hex: '#B8965A' },
      { name: 'Soft Rose', hex: '#C4A882' },
    ],
    fabric: 'Luxury Chiffon with Satin lining',
    details: [
      'Embellished cuff and collar detail',
      'Satin inner lining',
      'Closed-front with hidden snap buttons',
      'Floor-length with subtle train',
    ],
    careInstructions: ['Dry clean only', 'Store in garment bag', 'Do not wring or twist'],
  },
  {
    id: 'al-lail',
    name: 'Al Lail',
    category: 'Evening',
    description: 'For evenings that deserve a presence. Understated, deeply memorable.',
    price: '₹11,200',
    priceNum: 11200,
    tag: 'Evening',
    featured: false,
    aspect: 'portrait',
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Midnight Black', hex: '#141412' },
      { name: 'Dusty Mauve', hex: '#9B8B8B' },
    ],
    fabric: 'Premium Satin with Silk blend',
    details: [
      'Draped silhouette with pleat detail',
      'Hand-embroidered border at hem',
      'Concealed side pockets',
      'Fully lined in soft silk',
    ],
    careInstructions: ['Dry clean recommended', 'Steam to remove creases', 'Store flat in garment bag'],
  },
  {
    id: 'al-safa',
    name: 'Al Safa',
    category: 'Minimal',
    description: 'Simplicity elevated. A refined silhouette for every occasion.',
    price: '₹6,800',
    priceNum: 6800,
    tag: 'Classic',
    featured: false,
    aspect: 'portrait',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Midnight Black', hex: '#141412' },
      { name: 'Ivory Cream', hex: '#F8F4EE' },
      { name: 'Slate Grey', hex: '#6B6B6B' },
    ],
    fabric: '100% Nida Fabric',
    details: [
      'Clean A-line silhouette',
      'Snap button closure',
      'Minimal seam detailing',
      'Suitable for everyday wear',
    ],
    careInstructions: ['Machine wash cold', 'Hang dry', 'Iron on low heat'],
  },
  {
    id: 'al-hoor',
    name: 'Al Hoor',
    category: 'Limited',
    description: 'Our namesake. The pinnacle of what HOOR was always meant to create.',
    price: '₹14,500',
    priceNum: 14500,
    tag: 'Limited',
    featured: false,
    aspect: 'portrait',
    sizes: ['S', 'M', 'L', 'XL'],
    colors: [
      { name: 'Midnight Black', hex: '#141412' },
    ],
    fabric: 'Hand-selected Japanese Crepe with French Lace trim',
    details: [
      'One-of-a-kind embroidered panel at bodice',
      'French lace trim at cuffs and hem',
      'Bespoke pearl button placket',
      'Fully lined in premium silk',
      'Certificate of authenticity included',
    ],
    careInstructions: ['Dry clean only', 'Store in provided garment bag', 'Handle with care'],
  },
  {
    id: 'al-nada',
    name: 'Al Nada',
    category: 'Summer',
    description: 'Breathable linen in elegant form for warm days worn without compromise.',
    price: '₹6,200',
    priceNum: 6200,
    tag: 'Summer',
    featured: false,
    aspect: 'portrait',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Natural Linen', hex: '#D4C4A8' },
      { name: 'Sky Mist', hex: '#C4D4D8' },
      { name: 'Ivory Cream', hex: '#F8F4EE' },
    ],
    fabric: '100% Premium Linen',
    details: [
      'Relaxed open-front silhouette',
      'Natural linen texture',
      'Wide sleeves for airflow',
      'Lightweight for warm climates',
    ],
    careInstructions: ['Machine wash cold', 'Line dry in shade', 'Iron while slightly damp for best results'],
  },
  {
    id: 'al-fajr',
    name: 'Al Fajr',
    category: 'Prayer',
    description: 'Designed for the sacred. Softness, full coverage, and reverent grace.',
    price: '₹4,800',
    priceNum: 4800,
    tag: 'Prayer',
    featured: false,
    aspect: 'portrait',
    sizes: ['Free Size', 'S-M', 'L-XL', 'XXL'],
    colors: [
      { name: 'Pure White', hex: '#FAFAF8' },
      { name: 'Ivory Cream', hex: '#F8F4EE' },
      { name: 'Soft Sage', hex: '#C4C8B8' },
    ],
    fabric: 'Ultra-soft Jersey Knit',
    details: [
      'Full coverage with integrated head covering',
      'Stretchy jersey for ease of movement',
      'No buttons or zippers',
      'Machine washable',
    ],
    careInstructions: ['Machine wash warm', 'Tumble dry low', 'Do not bleach'],
  },
  {
    id: 'al-safar',
    name: 'Al Safar',
    category: 'Travel',
    description: 'Wrinkle-resistant, effortlessly packable. Elegance on every journey.',
    price: '₹7,600',
    priceNum: 7600,
    tag: 'Travel',
    featured: false,
    aspect: 'portrait',
    sizes: ['XS', 'S', 'M', 'L', 'XL', 'XXL'],
    colors: [
      { name: 'Midnight Black', hex: '#141412' },
      { name: 'Deep Navy', hex: '#1B2A4A' },
      { name: 'Mocha Nude', hex: '#D4B8A8' },
    ],
    fabric: 'Wrinkle-resistant Polyester Crepe',
    details: [
      'Packable and lightweight',
      'Wrinkle-resistant fabric technology',
      'Dual side pockets',
      'Adjustable cuff tabs',
    ],
    careInstructions: ['Machine wash cold', 'Tumble dry low', 'Minimal ironing required'],
  },
]

export const ABAYA_TYPES: AbayanType[] = [
  { id: 'classic',   name: 'Classic',   description: 'Refined simplicity for daily grace. Timeless silhouettes that never demand attention, yet always earn it.',              icon: '◈' },
  { id: 'signature', name: 'Signature', description: 'Our most coveted pieces — elevated craftsmanship and luxurious fabrics for moments that deserve to be remembered.',     icon: '✦' },
  { id: 'luxury',    name: 'Luxury',    description: 'The finest materials, the most considered finishes. For the woman who understands that quality speaks in silence.',      icon: '◆' },
  { id: 'evening',   name: 'Evening',   description: 'Designed for unforgettable evenings. Premium fabrics that catch light gracefully and silhouettes that command presence.', icon: '◎' },
]

export const TESTIMONIALS: Testimonial[] = [
  { id: '1', name: 'Fathima Rizwan',   location: '',  rating: 5, quote: 'I have never felt this beautiful in an abaya before. The fabric is so soft and the fit is perfect. Shiza really understands what we want.' },
  { id: '2', name: 'Samira Noor',      location: '',  rating: 5, quote: 'Ordered the black one for Eid and got so many compliments. The quality is far better than anything I have bought online before. Will definitely order again.' },
  { id: '3', name: 'Aisha Binth Salim',location: '',  rating: 5, quote: 'Finally a brand that does not compromise on modesty or style. The stitching is clean, the fabric drapes beautifully, and delivery was so fast.' },
  { id: '4', name: 'Ruhana Faisal',    location: '',  rating: 5, quote: 'My mother and I both ordered and we both love it. This is the kind of quality you expect to pay double for. HOOR is genuinely different.' },
  { id: '5', name: 'Nida Rasheed',     location: '',  rating: 5, quote: 'Wore it to a family wedding and everyone kept asking where I got it from. Simple, elegant, and so well made. Exactly what I was looking for.' },
  { id: '6', name: 'Zainab Haroon',    location: '',  rating: 5, quote: 'The packaging itself felt like a gift. But the abaya inside was even better. Every detail is thought through. Highly recommend HOOR to everyone.' },
]

export const WHY_HOOR = [
  { title: 'Premium Quality',   body: 'Every piece starts with carefully sourced materials silks, linens, and specialty weaves selected for their exceptional feel and look.', icon: '◈' },
  { title: 'Careful Finishing', body: 'Each abaya is put together with precision and attention to detail. Quality that shows in every hem, every edge, every finish.',              icon: '✦' },
  { title: 'Thoughtful Design', body: 'Our silhouettes are shaped for modern women — flattering, functional, and suited for the full spectrum of daily life.',                    icon: '◇' },
  { title: 'Timeless Approach', body: 'HOOR does not follow trends. Every piece is chosen to be worn for years and remembered for even longer.',                                   icon: '○' },
]
